### ISSUE TITLE
How do I make local git meet criteria for sub projects per branch?

### ISSUE THREAD

**Issue by pescadorbob** [jglick/github-branch-source-plugin#1]
I am trying to run this plugin against git repositories on my local machine using a git location such as: file://D:\work\go-projects\framework

I have several branches created there, master and develop.  But when I save the multi-branch project with this repository, the branch indexing displays the following:

``` Started
Setting origin to file://D:\work\go-projects\framework
Fetching origin...
Pruning stale remotes...
Getting remote branches...
Checking branch development
Does not meet criteria
Checking branch master
Does not meet criteria
Done.
Finished: SUCCESS
```

If I run against some other examples on Git Hub, it all works fine.  Is there a way to run against local git repositories?

In looking at the code, the criteria condition is possibly contained in `OriginGitHubSCMSource` line 71 `if (branchCriteria.isHead(probe, listener))`.  How can I make that condition respond `true` for a local repository?

**Comment by jglick** [comment]
Use JIRA please.
