### ISSUE TITLE
Removing deleted branches and closed Pull requests

### ISSUE THREAD

**Issue by thisismana** [jglick/github-branch-source-plugin#3]
Thank you for this wonderful plugin, it seems to be a very good bridge between GitHub and the Jenkins pipeline plugins.

I've managed to set the whole thing up, including pull-requests. 

Question: Ho to delete branches -- also closed and deleted pull-requests -- removed from the projects folder in Jenkins? Or is it intended to have one job for each pull request build that lives "forever"?

**Comment by MichaelGreco** [comment]
Yeah exactly .. If the jobs generated created could be configured to capture "branch delete" and "pr close" events and then the jobs could run a Jenkinsfile out of a named branch (which would be a global job config setting). Then the code in the Jenkinsfile of that named branch could take an action (like delete cloud resources that were used for testing prior to  closing/deleting the PR/BRANCH).

**Comment by jglick** [comment]
Use JIRA please.
